source 'https://github.com/CocoaPods/Specs.git'

target :GTFoundation do
	platform :ios, "7.0" 
	pod "GTFoundation", :path => "../GTFoundation.podspec"
end

target :GTFoundationMac do
	platform :osx, "10.9"
	pod "GTFoundation", :path => "../GTFoundation.podspec"
end